languageCode = "en-us"
title = "Prologue"
baseurl = "https://noltron000.github.io/my-website"
theme = "prologue"
publishDir = "docs"
relativeURLs = true

[params]
  name = "Nolan Kovacik"
  avatar = "https://avatars2.githubusercontent.com/u/19766927?s=460&v=4"
  image ="https://images.pexels.com/photos/52533/orange-fruit-vitamins-healthy-eating-52533.jpeg?h=350&dpr=2&auto=compress&cs=tinysrgb"
  description = "Software Engineer"
  copyright = "©️ 2017"
  twitter = "noltron000"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "//twitter.com/noltron000"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "dribbble"
  icon = "dribbble"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "#"

# Portfolio column one

[[params.portfolio1]]
  title = "Portfolio 1"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Portfolio 2"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Portfolio 3"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Portfolio 4"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Portfolio 5"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Portfolio 6"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
